# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DraftServiceStub(object):
    """Service for draft (small) model operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/speculative.DraftService/LoadModel',
                request_serializer=inference__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=inference__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/speculative.DraftService/StartSession',
                request_serializer=inference__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.GenerateDraft = channel.unary_unary(
                '/speculative.DraftService/GenerateDraft',
                request_serializer=inference__pb2.GenerateDraftRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerateDraftResponse.FromString,
                _registered_method=True)
        self.UpdateDraftContext = channel.unary_unary(
                '/speculative.DraftService/UpdateDraftContext',
                request_serializer=inference__pb2.UpdateDraftContextRequest.SerializeToString,
                response_deserializer=inference__pb2.UpdateDraftContextResponse.FromString,
                _registered_method=True)


class DraftServiceServicer(object):
    """Service for draft (small) model operations
    """

    def LoadModel(self, request, context):
        """Load the draft model (e.g., Meta LLaMA small model) on the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Start a new decoding session with a given prompt (context)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDraft(self, request, context):
        """Generate a speculative draft of tokens from the draft model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDraftContext(self, request, context):
        """Update the draft model context after speculative decoding (rollback and new token integration)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DraftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=inference__pb2.LoadModelRequest.FromString,
                    response_serializer=inference__pb2.LoadModelResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=inference__pb2.StartSessionRequest.FromString,
                    response_serializer=inference__pb2.StartSessionResponse.SerializeToString,
            ),
            'GenerateDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDraft,
                    request_deserializer=inference__pb2.GenerateDraftRequest.FromString,
                    response_serializer=inference__pb2.GenerateDraftResponse.SerializeToString,
            ),
            'UpdateDraftContext': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDraftContext,
                    request_deserializer=inference__pb2.UpdateDraftContextRequest.FromString,
                    response_serializer=inference__pb2.UpdateDraftContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speculative.DraftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speculative.DraftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DraftService(object):
    """Service for draft (small) model operations
    """

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.DraftService/LoadModel',
            inference__pb2.LoadModelRequest.SerializeToString,
            inference__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.DraftService/StartSession',
            inference__pb2.StartSessionRequest.SerializeToString,
            inference__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.DraftService/GenerateDraft',
            inference__pb2.GenerateDraftRequest.SerializeToString,
            inference__pb2.GenerateDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDraftContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.DraftService/UpdateDraftContext',
            inference__pb2.UpdateDraftContextRequest.SerializeToString,
            inference__pb2.UpdateDraftContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TargetServiceStub(object):
    """Service for target (large) model operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/speculative.TargetService/LoadModel',
                request_serializer=inference__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=inference__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/speculative.TargetService/StartSession',
                request_serializer=inference__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.CheckTokenProbability = channel.unary_unary(
                '/speculative.TargetService/CheckTokenProbability',
                request_serializer=inference__pb2.CheckTokenRequest.SerializeToString,
                response_deserializer=inference__pb2.CheckTokenResponse.FromString,
                _registered_method=True)
        self.AppendToken = channel.unary_unary(
                '/speculative.TargetService/AppendToken',
                request_serializer=inference__pb2.AppendTokenRequest.SerializeToString,
                response_deserializer=inference__pb2.AppendTokenResponse.FromString,
                _registered_method=True)
        self.GenerateTargetToken = channel.unary_unary(
                '/speculative.TargetService/GenerateTargetToken',
                request_serializer=inference__pb2.GenerateTargetRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerateTargetResponse.FromString,
                _registered_method=True)


class TargetServiceServicer(object):
    """Service for target (large) model operations
    """

    def LoadModel(self, request, context):
        """Load the target model (e.g., LLaMA large model) on the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Start a new decoding session with a given prompt (context)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTokenProbability(self, request, context):
        """Check acceptance probability of a draft token with the target model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendToken(self, request, context):
        """Append an accepted token to the target context (updates KV cache and prepares next distribution)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTargetToken(self, request, context):
        """Generate the next target token when draft tokens are exhausted or rejected (handles finalization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TargetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=inference__pb2.LoadModelRequest.FromString,
                    response_serializer=inference__pb2.LoadModelResponse.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=inference__pb2.StartSessionRequest.FromString,
                    response_serializer=inference__pb2.StartSessionResponse.SerializeToString,
            ),
            'CheckTokenProbability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTokenProbability,
                    request_deserializer=inference__pb2.CheckTokenRequest.FromString,
                    response_serializer=inference__pb2.CheckTokenResponse.SerializeToString,
            ),
            'AppendToken': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendToken,
                    request_deserializer=inference__pb2.AppendTokenRequest.FromString,
                    response_serializer=inference__pb2.AppendTokenResponse.SerializeToString,
            ),
            'GenerateTargetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTargetToken,
                    request_deserializer=inference__pb2.GenerateTargetRequest.FromString,
                    response_serializer=inference__pb2.GenerateTargetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speculative.TargetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speculative.TargetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TargetService(object):
    """Service for target (large) model operations
    """

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.TargetService/LoadModel',
            inference__pb2.LoadModelRequest.SerializeToString,
            inference__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.TargetService/StartSession',
            inference__pb2.StartSessionRequest.SerializeToString,
            inference__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckTokenProbability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.TargetService/CheckTokenProbability',
            inference__pb2.CheckTokenRequest.SerializeToString,
            inference__pb2.CheckTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.TargetService/AppendToken',
            inference__pb2.AppendTokenRequest.SerializeToString,
            inference__pb2.AppendTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTargetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speculative.TargetService/GenerateTargetToken',
            inference__pb2.GenerateTargetRequest.SerializeToString,
            inference__pb2.GenerateTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
